{
 "title": "JFrog Platform Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Upload Data Transfers",
   "type": "graph",
   "description": "Shows the upload data transfers from this Artifactory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(jfrog_rt_data_upload)" }
   ]
  },
  {
   "title": "Download Data Transfers",
   "type": "graph",
   "description": "Shows the download data transfers from this Artifactory.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(jfrog_rt_data_download)" }
   ]
  },
  {
   "title": "Top Downloading IPs",
   "type": "bargauge",
   "description": "Shows the top downloading remote IPs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (jfrog_rt_data_download))",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "Top Uploading IPs",
   "type": "bargauge",
   "description": "Shows the top uploading IPs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (jfrog_rt_data_upload))",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "Top Artifacts by Requests",
   "type": "bargauge",
   "description": "Shows the top artifacts that have been requested.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by (artifact) (jfrog_rt_req{artifact!=\"\"}))",
     "legendFormat": "{{artifact}}"
    }
   ]
  },
  {
   "title": "Top Repos by Requests",
   "type": "bargauge",
   "description": "Shows the top repositories by requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (jfrog_rt_req{repo!=\"\"}) )",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Audit Users",
   "type": "bargauge",
   "description": "Shows the top users by actions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "topk(10, sum by (user) (jfrog_rt_access_audit{user!=\"UNKNOWN\"}) )",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Top Active Repos by Data",
   "type": "bargauge",
   "description": "Top active repositories by data transfers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (jfrog_rt_data_download) )",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Artifactory 5xx Status Codes",
   "type": "graph",
   "description": "Shows Artifactory 5XX errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jfrog_rt_req{return_status=~\"5.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Artifactory User Access",
   "type": "bargauge",
   "description": "Shows top users.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (jfrog_rt_access))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Artifactory Errors",
   "type": "graph",
   "description": "Shows Artifactory errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jfrog_rt_log_level{log_level=\"ERROR\"}[5m])"
    }
   ]
  },
  {
   "title": "Denied Login Attempts",
   "type": "bargauge",
   "description": "Shows the denied login attempts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(10, sum by (ip,username) (jfrog_rt_access{action_response=\"DENIED LOGIN\"}) )",
     "legendFormat": "{{username}}-{{ip}}"
    }
   ]
  },
  {
   "title": "Xray 5xx Status Codes",
   "type": "graph",
   "description": "Shows Xray 5XX errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jfrog_xray_req{return_status=~\"5.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Top Accepted Deploys by Username",
   "type": "bargauge",
   "description": "Shows accepted deploys by username.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (jfrog_rt_access{action_response=\"ACCEPTED DEPLOY\"}) )",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Xray Errors",
   "type": "graph",
   "description": "Shows Xray errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jfrog_xray_log_level{log_level=\"ERROR\"}[5m])"
    }
   ]
  },
  {
   "title": "Denied Actions by IP",
   "type": "bargauge",
   "description": "Shows denied actions by IP address.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (jfrog_rt_access{action_response=\"DENIED\"}) )",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Denied Actions by Username",
   "type": "bargauge",
   "description": "Shows denied actions by username.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (jfrog_rt_access{action_response=\"DENIED\"}) )",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}